### ISSUE TITLE
Add a get version command

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/EPS_FlightSoftware#7] opened 2019-11-28 13:30 UTC
It is important for traceability to add a command showing which software version is running, possibly getting git hash...

**Comment by CasperBroekhuizen** [comment] 2020-01-09 13:05
Duplicate of https://github.com/DelfiSpace/FlightSoftwareWorkspace/issues/3

**Comment by CasperBroekhuizen** [comment] 2020-01-22 08:50
Closed, as this is a duplicate ^

**Closed as completed by CasperBroekhuizen** 2020-01-22 08:50 UTC
